# Generated by Django 5.0.1 on 2024-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_foodgallerycategory_foodgallery_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodGalleryCategory',
            new_name='FoodGalleryCategoryModel',
        ),
        migrations.RenameModel(
            old_name='FoodGallery',
            new_name='FoodGalleryModel',
        ),
    ]
