# Generated by Django 5.0.1 on 2024-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_foodgallerycategory_foodgallerycategorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgallerymodel',
            name='category',
        ),
        migrations.AddField(
            model_name='foodgallerymodel',
            name='category',
            field=models.ManyToManyField(null=True, to='page.foodgallerycategorymodel'),
        ),
    ]
