# Generated by Django 5.0.1 on 2024-01-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReservationModel',
        ),
    ]
