# Generated by Django 5.0.1 on 2024-01-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_subscribemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribemodel',
            old_name='email',
            new_name='form_subscribe',
        ),
    ]
