# Generated by Django 5.0.1 on 2024-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_menumodelcategory_menumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='icons',
            field=models.ImageField(null=True, upload_to='Menu_icons'),
        ),
    ]
