# Generated by Django 5.0.1 on 2024-01-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_menumodel_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='comments')),
                ('first_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='icons',
            field=models.ImageField(upload_to='Menu_icons'),
        ),
    ]
