# Generated by Django 5.0.1 on 2024-01-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='place',
        ),
    ]
