# Generated by Django 5.0.1 on 2024-01-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_rename_date_events_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
