# Generated by Django 5.0.1 on 2024-01-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chef_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
