# Generated by Django 5.0.1 on 2024-01-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_chefmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefmodel',
            name='icon',
            field=models.ImageField(null=True, upload_to='chef_icon'),
        ),
    ]
