# Generated by Django 5.0 on 2023-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('main', models.CharField(max_length=20)),
            ],
        ),
    ]
