# Generated by Django 5.0 on 2023-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0003_rename_country_weather_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('icon', models.ImageField(upload_to='weather')),
            ],
        ),
    ]
