# Generated by Django 5.0 on 2023-12-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0004_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='icon',
        ),
    ]
